SERVER_PACKET_SIZE = 8192
TASK_SPLIT = ":"

DEPLOY_SERVER_LOGIN = "00"
DEPLOY_SERVER_LOGIN_SUCCESS = DEPLOY_SERVER_LOGIN + TASK_SPLIT + "00"
DEPLOY_SERVER_LOGIN_FAIL = DEPLOY_SERVER_LOGIN + TASK_SPLIT + "01"

DEPLOY_SERVER_ASSIGN = "01"
DEPLOY_SERVER_ASSIGN_COMPLETE = DEPLOY_SERVER_ASSIGN + TASK_SPLIT + "00"
DEPLOY_SERVER_ASSIGN_FAIL = DEPLOY_SERVER_ASSIGN + TASK_SPLIT + "01"

CLIENT_LOGIN = "10"
CLIENT_LOGIN_SUCCESS = CLIENT_LOGIN + TASK_SPLIT + "00"
CLIENT_LOGIN_FAIL = CLIENT_LOGIN + TASK_SPLIT + "01"

CLIENT_ASSIGN = "11"
CLIENT_ASSIGN_SUCCESS = CLIENT_ASSIGN + TASK_SPLIT + "00"
CLIENT_ASSIGN_FAIL = CLIENT_ASSIGN + TASK_SPLIT + "01"

