# .travis.yml
language: python
python:
    - "3.8"

before_install:
    - python --version
    - pip install -U pip
    - pip install codecov

install:
    - pip install -r requirements.txt
    - python download_model.py
    
script:
    - coverage run --omit="*/test*" -m unittest test.py

after_success:
    - codecov
