
SERVER_IP = "localhost"
SERVER_PORT = 7777
SERVER_PACKET_SIZE = 1024

TASK_SPLIT = ";"

USER_REGISTER = "00"
USER_REGISTER_SUCCESS = USER_REGISTER + TASK_SPLIT + "00"
USER_REGISTER_FAIL = USER_REGISTER + TASK_SPLIT + "01"

USER_LOGIN = "01"
USER_LOGIN_SUCCESS = USER_LOGIN + TASK_SPLIT + "00"
USER_LOGIN_FAIL = USER_LOGIN + TASK_SPLIT + "01"
USER_LOGIN_SERVER_ERR = USER_LOGIN + TASK_SPLIT + "02"
USER_LOGIN_CLIENT_ERR = USER_LOGIN + TASK_SPLIT + "03"

